#!/bin/bash

echo
echo "[✔] raspi-ap package installed successfully!"
echo

/usr/local/bin/config-raspi-ap

echo
echo "Available commands:"
echo "  🔹 sudo start-raspi-ap           → Start the Raspberry Pi access point"
echo "  🔹 sudo stop-raspi-ap            → Stop the access point and revert config"
echo "  🔹 sudo enable-raspi-ap          → Enable auto-start on boot"
echo "  🔹 sudo disable-raspi-ap         → Disable auto-start on boot"
echo "  🔹 sudo config-raspi-ap          → Reconfigure SSID and password"
echo "  🔹 sudo enable-network-watcher   → Start and enable network watcher on boot"
echo "  🔹 sudo disable-network-watcher  → Stop and disable network watcher on boot"
echo "  🔹 sudo status-network-watcher   → Display logs of changes in network"
echo "  🔹 sudo config-wifi              → Reconfigure fallback Wi-Fi for post-AP reconnect"
