#!/bin/bash

echo
echo "[✔] raspi-ap package installed successfully!"
echo
echo "Available commands:"
echo "  🔹 sudo start-raspi-ap     → Start the Raspberry Pi access point"
echo "  🔹 sudo stop-raspi-ap      → Stop the access point and revert config"
echo "  🔹 sudo enable-raspi-ap    → Register the AP to auto-start on boot"
echo "  🔹 sudo disable-raspi-ap   → Unregister auto-start on boot"
